ALTER TABLE `charlog` MODIFY `time` DATETIME DEFAULT NULL;
ALTER TABLE `interlog` MODIFY `time` DATETIME DEFAULT NULL;
ALTER TABLE `ipbanlist` MODIFY `btime` DATETIME DEFAULT NULL;
ALTER TABLE `ipbanlist` MODIFY `rtime` DATETIME DEFAULT NULL;
ALTER TABLE `login` MODIFY `lastlogin` DATETIME DEFAULT NULL;
ALTER TABLE `login` MODIFY `birthdate` DATETIME DEFAULT NULL;
